### ISSUE TITLE
Update video view to display data dynamically

### ISSUE THREAD

**Issue by mmacquarrie** [mmacquarrie/reelfeels#25]
also add 'video/id' mapping to urls

**Comment by mbrubin** [comment]
My commit 3/25/18:
TO-DO: 
- fix User profile_pic file upload location (involves MEDIA_ROOT/URL in settings.py)
- figure out which id is used in url /.../video/<id> (is it the Video's id? or the Upload's id? ...)

Here's a sample of a valid video url: http://127.0.0.1:8000/video/VnZEpic2UzU

**Comment by mbrubin** [comment]
Re-opening with new to-dos:
- fix (again) user profile_pic upload file location stuff (_it must actually place the image file in the specified static/media location!_)
- clean up the video_content view; pass in just a single "video" and "uploader" variable to context so that I don't need to pass a million different variables into the context
